// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd-3Yi1tQ2jc4vx8Vjmt0OOxH1C4FFKWc',
    appId: '1:411688234267:android:227c57a5f29809a1d9f7be',
    messagingSenderId: '411688234267',
    projectId: 'message-c7708',
    databaseURL: 'https://message-c7708-default-rtdb.firebaseio.com',
    storageBucket: 'message-c7708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7n0VKLKFe7IEZPdoZPN8Y_jBqABDHh-A',
    appId: '1:411688234267:ios:e2c8a84ad595a757d9f7be',
    messagingSenderId: '411688234267',
    projectId: 'message-c7708',
    databaseURL: 'https://message-c7708-default-rtdb.firebaseio.com',
    storageBucket: 'message-c7708.appspot.com',
    iosBundleId: 'com.example.secureMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7n0VKLKFe7IEZPdoZPN8Y_jBqABDHh-A',
    appId: '1:411688234267:ios:e2c8a84ad595a757d9f7be',
    messagingSenderId: '411688234267',
    projectId: 'message-c7708',
    databaseURL: 'https://message-c7708-default-rtdb.firebaseio.com',
    storageBucket: 'message-c7708.appspot.com',
    iosBundleId: 'com.example.secureMessenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz7at7O3SbNoMT6iV42AltTRPt-T1mIAQ',
    appId: '1:411688234267:web:d9a5a7bc7e12c536d9f7be',
    messagingSenderId: '411688234267',
    projectId: 'message-c7708',
    authDomain: 'message-c7708.firebaseapp.com',
    databaseURL: 'https://message-c7708-default-rtdb.firebaseio.com',
    storageBucket: 'message-c7708.appspot.com',
  );
}
